import type React from "react"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { ThemeProvider } from "@/components/theme-provider"
import { AppInit } from "@/components/app-init"
import { QueryProvider } from "@/components/query-provider"
import { BrowserRouter } from "react-router-dom"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  generator: "v0.dev",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <AppInit />
          <QueryProvider>
            <BrowserRouter>{children}</BrowserRouter>
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
